apiVersion: apps/v1
kind: Deployment
metadata:
  name: derpfad
  labels:
    app: derpfad
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: derpfad
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: derpfad
    spec:
      containers:
      - name: derpfad
        image: registry.digitalocean.com/kephalosk/derpfad:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: derpfad
  name: derpfad-service
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: derpfad
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: watchfromtheshore@gmail.com # Change to your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: derpfad-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: easywebpath.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: derpfad-service
                port:
                  number: 80
    - host: www.easywebpath.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: derpfad-service
                port:
                  number: 80
  tls:
    - hosts:
        - easywebpath.com
        - www.easywebpath.com
      secretName: derpfad-tls