apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimalhtml
  labels:
    app: minimalhtml
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: minimalhtml
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: minimalhtml
    spec:
      containers:
      - name: minimalhtml
        image: registry.digitalocean.com/kephalosk/derpfad:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: minimalhtml
  name: minimalhtml
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32573
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: minimalhtml
  sessionAffinity: None
  type: LoadBalancer