version: "25"
services:
  wordpress:
    image: wordpress
    ports:
      - "8089:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "derpfad"
      WORDPRESS_DB_NAME: wordpress
  mysql:
    image: "mysql:8.4"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "derpfad"
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  derpfad:
    ipam:
      driver: default