

# This workfow shows how to build a Docker image, tag and push it to DigitalOcean Container Registry, and
# deploy the application on a DIgitalOcean Kubernetes cluster. For description to the entire worklow, 
# see www.digitalocean.com/docs/kubernetes/how-to/deploy-using-github-actions.

name: Build, push, and deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push request on the main branch for changes in the specified paths.
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    # old:      uses: actions/checkout@v2
    - name: Checkout master
      uses: actions/checkout@main

    # Install doctl.
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    # Build a Docker image of your application in your registry and tag the image with the $GITHUB_SHA.
    - name: Build container image
      run: docker build -t derpfad:latest .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Tag image
      run: docker tag derpfad:latest registry.digitalocean.com/kephalosk/derpfad:latest
      
    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/kephalosk/derpfad:latest

    - name: Renew cluster’s certificate
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_ID }}

    # Deploy to DigitalOCcean Kubernetes.
    - name: Deploy to DigitalOcean Kubernetes
      run: |
        sed -i "s/{{ timestamp }}/$(date +%s)/g" derpfad.yaml
        kubectl apply -f derpfad.yaml

    - name: Verify deployment
      run: kubectl rollout status deployment/derpfad
